version: '3'
services:
  volunteer-app:
    image: volunteer-springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports: # 80 web and 9090 mobile
      - "80:8080"
      - "9090:8080"
    volumes:
      - ./target:/app
