version: '3'
services:
  volunteer-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: volunteer-springboot-app
    ports:
      - "80:8080"   # acesso web público via porta 80
      - "9090:8080" # porta alternativa para mobile/testes
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
