spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/volunteer-test}
  kafka:
    listener:
      auto-startup: false

app:
  kafka:
    enabled: false

firebase:
  enabled: false
