spring:
  application:
    name: VolunteerModel
  server:
    address: 0.0.0.0
    port: 8080
    servlet:
      context-path: /volunteer

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP:user-registration-events-consumer}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  profile:
    active: prod

  jpa:
    open-in-view: false

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      mappings:
        enabled: true