spring:
  data:
    mongodb:
      uri: mongodb+srv://fabianodspereira:Y7UUiDh0bbjmGlxE@volunteers.znrcbmn.mongodb.net/volunteer

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: false