spring:
  application:
    name: Volunteer
  server:
    address: 0.0.0.0
    port: 8080
    servlet:
      context-path: /volunteer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-registration-events-consumer
      properties:
        zookeeper.connect: localhost:2181

  profile:
    active: prod

  jpa:
    open-in-view: false

  management:
    # Desabilita métricas que quebram no container slim
    metrics:
      enable:
        processors: false
        jvm: false
        system: false
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      mappings:
        enabled: true